I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 12, in script
    m "Hey... Umm..."
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 12, in script
    m "Hey... Umm..."
  File "C:\Users\Ruby W\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Ruby W\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'm' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
CRC RIZZ 1.0
Sat Sep 23 10:49:37 2023
